### ISSUE TITLE
ModuleNotFoundError: No module named 'urlparse'

### ISSUE THREAD

**Issue by sangjianshun** [tencentyun/qcloud-documents#8085]
Traceback (most recent call last):
  File "CosOperate.py", line 13, in <module>
    from qcloud_cos import CosConfig
  File "/root/py36/lib/python3.6/site-packages/qcloud_cos/__init__.py", line 3, in <module>
    from .cos import Cos
  File "/root/py36/lib/python3.6/site-packages/qcloud_cos/cos.py", line 12, in <module>
    from .auth import Auth
  File "/root/py36/lib/python3.6/site-packages/qcloud_cos/auth.py", line 8, in <module>
    from urlparse import urlparse
ModuleNotFoundError: No module named 'urlparse'

**Comment by vgyyuangao** [comment]
尊敬的腾讯云用户，您好！
如果遇到产品相关问题，您可以咨询 [在线客服](https://cloud.tencent.com/act/event/Online_service) 或 [提交工单](https://console.cloud.tencent.com/workorder/category) 寻求帮助，非常感谢！
另外，腾讯云文档有“文档反馈”的功能，您也可以直接在文档页面进行反馈，反馈还有可能获得 [礼品](https://cloud.tencent.com/developer/article/1523112) ~
